TAG_DICT = {
    "touhou": "(Touhou OR Touhou Project OR 東方 OR 東方Project)",

    "reimu": "(reimu hakurei)",
    "marisa": "(marisa kirisame)",

    "rumia": "(rumia)",
    "daiyousei": "(daiyousei)",
    "cirno": "(cirno)",
    "meiling": "(hong meiling)",
    "koakuma": "(koakuma)",
    "patchouli": "(patchouli knowledge)",
    "sakuya": "(sakuya izayoi)",
    "remilia": "(remilia scarlet)",
    "flandre": "(flandre scarlet)",

    "letty": "(letty whiterock)",
    "chen": "(Chen)",
    "alice": "(alice margatroid)",
    "lily": "(lily white)",
    "lunasa": "(lunasa prismriver)",
    "merlin": "(merlin prismriver)",
    "lyrica": "(lyrica prismriver)",
    "youmu": "(youmu konpaku)",
    "yuyuko": "(yuyuko saigyouji)",
    "ran": "(ran yakumo)",
    "yukari": "(yukari yakumo)",

    "suika": "(suika ibuki)",

    "wriggle": "(wriggle nightbug)",
    "mystia": "(mystia lorelei)",
    "keine": "(keine kamishirasawa)",
    "tewi": "(tewi inaba)",
    "reisen": "(reisen udongein inaba)",
    "eirin": "(eirin yagokoro)",
    "kaguya": "(kaguya houraisan)",
    "mokou": "(fujiwara no mokou)",

    "medicine": "(medicine melancholy)",
    "yuuka": "(yuuka kazami)",
    "komachi": "(komachi onozuka)",
    "shikieiki": "(shiki eiki yamazanadu)",

    "shizuha": "(shizuha aki)",
    "minoriko": "(minoriko aki)",
    "hina": "(hina kagiyama)",
    "nitori": "(nitori kawashiro)",
    "momiji": "(momiji inubashiri)",
    "aya": "(aya shameimaru)",
    "sanae": "(sanae kochiya)",
    "kanako": "(kanako yasaka)",
    "suwako": "(suwako moriya)",
}